[package]
name = "transiter_types_no_std"
version = "0.1.0"
edition = "2021"
authors = ["Diego Aristides Marcano Aranguren"]
description = "Some generated rust types for the transiter API https://github.com/jamespfennell/transiter. Meant for no std enviromnets that have an alloc. "

[dependencies]
prost = { version = "0.13.4", default-features = false, features = ["prost-derive"] }
serde = {version = "^1.0", features = ["derive", "alloc"], default-features = false}
serde-json-core = "^0.6"

[build-dependencies]
tonic-build = "0.11.0"
